In [1]:
### Tutorial on how to iterate over a matrix columns and rows in Python,
### using the numpy library.

import numpy as np

# Create a matrix
matrix = np.array([[i for i in range(5)], 
                    [i for i in range(5, 10)], 
                    [i for i in range(10, 15)],
                    [i for i in range(15, 20)],
                    [i for i in range(20, 25)]])
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
#perform a row-wise operation
nrows = matrix.shape[0]
ncols = matrix.shape[1]
for i in range(nrows):
    if i < 2:
        print(matrix[i,:])
    else:
        break

[0 1 2 3 4]
[5 6 7 8 9]


In [3]:
#perform a row-wise and column-wise operation
for i in range(nrows):
    print(f"We are at row: {i+1}")
    for j in range(ncols):
        print(f"We are at column: {j+1}")
        print(matrix[i,j])

We are at row: 1
We are at column: 1
0
We are at column: 2
1
We are at column: 3
2
We are at column: 4
3
We are at column: 5
4
We are at row: 2
We are at column: 1
5
We are at column: 2
6
We are at column: 3
7
We are at column: 4
8
We are at column: 5
9
We are at row: 3
We are at column: 1
10
We are at column: 2
11
We are at column: 3
12
We are at column: 4
13
We are at column: 5
14
We are at row: 4
We are at column: 1
15
We are at column: 2
16
We are at column: 3
17
We are at column: 4
18
We are at column: 5
19
We are at row: 5
We are at column: 1
20
We are at column: 2
21
We are at column: 3
22
We are at column: 4
23
We are at column: 5
24


In [4]:
for i in range(nrows):
    for j in range(ncols):
        v1 = matrix[i,:] + matrix[:,j]
        print(f"Sum of row {i+1} and column {j+1} is: {v1}")

Sum of row 1 and column 1 is: [ 0  6 12 18 24]
Sum of row 1 and column 2 is: [ 1  7 13 19 25]
Sum of row 1 and column 3 is: [ 2  8 14 20 26]
Sum of row 1 and column 4 is: [ 3  9 15 21 27]
Sum of row 1 and column 5 is: [ 4 10 16 22 28]
Sum of row 2 and column 1 is: [ 5 11 17 23 29]
Sum of row 2 and column 2 is: [ 6 12 18 24 30]
Sum of row 2 and column 3 is: [ 7 13 19 25 31]
Sum of row 2 and column 4 is: [ 8 14 20 26 32]
Sum of row 2 and column 5 is: [ 9 15 21 27 33]
Sum of row 3 and column 1 is: [10 16 22 28 34]
Sum of row 3 and column 2 is: [11 17 23 29 35]
Sum of row 3 and column 3 is: [12 18 24 30 36]
Sum of row 3 and column 4 is: [13 19 25 31 37]
Sum of row 3 and column 5 is: [14 20 26 32 38]
Sum of row 4 and column 1 is: [15 21 27 33 39]
Sum of row 4 and column 2 is: [16 22 28 34 40]
Sum of row 4 and column 3 is: [17 23 29 35 41]
Sum of row 4 and column 4 is: [18 24 30 36 42]
Sum of row 4 and column 5 is: [19 25 31 37 43]
Sum of row 5 and column 1 is: [20 26 32 38 44]
Sum of row 5 